[숫자 야구 게임] 박준영 과제 제출합니다.
LandvibeDev/java-baseball pull request #1
Opened 2023-06-27 14:19 UTC by farmJun

2023-06-27 15:07 UTC, KeonHee requested changes
기능적으로는 완벽하네요 👍 

남은 시간 리팩토링에 집중해봅시다.

2023-06-27 15:07 UTC, KeonHee commented on src/main/java/baseball/Application.java
> +	public static String generateRandomNumber() {
랜덤 넘버를 생성하는 함수인데 리턴 타입이 String인 것이 어색합니다.

다른 리턴 타입으로 바꿔봅시다.

2023-06-27 15:07 UTC, KeonHee commented on src/main/java/baseball/Application.java
> +		if (userGuessNumber.contains("0")) {
number range가 1-8, 2-5로 변경 되더라도 로직이 크게 변하지 않도록 리팩토링 해보세요

2023-06-27 15:07 UTC, KeonHee commented on src/main/java/baseball/Application.java
> +	public static int calculateStrikeCount(String randomNumber, String userGuessNumber) {
strike와 ball을 계산하는 로직을 하나의 함수로 합쳐보세요

2023-06-27 15:07 UTC, KeonHee commented on src/main/java/baseball/Application.java
> +	public static void printHint(String randomNumber, String userGuessNumber) {
계산과 출력을 분리하는 것이 좋습니다.
- 계산 함수 -> 결과 -> 출력 함수

2023-06-27 15:07 UTC, KeonHee commented on src/main/java/baseball/Application.java
> +	public static void main(String[] args) {
이 메소드를 제외하고 다른 메소드들을 클래스로 만들어보세요.

2023-06-27 15:26 UTC, sunwootest reviewed
전반적으로 잘 구현하셨습니다!

몇가지 개선사항을 적어보자면
- static 메소드가 이렇게 많을 필요가 있는가? 아마 `main()`안에 메소드를 실행하려다보니 그렇게 된 것 같네요.
- 상수값들이 하드 코딩 되어있습니다. 따로 분리하여 참조하는 편이 나아보입니다.
- 주석을 남용할 필요는 없습니다. 주석은 꼭 필요할 때만 작성하는 것이 좋습니다. 어떤 상황에서 주석을 작성해야하는지 알아보세요.

2023-06-27 15:26 UTC, sunwootest commented on src/main/java/baseball/Application.java
> +		}
1.2와 같은 길이가 3인 문자열은 걸러내지 못하네요 :)

코드를 읽었을 때 직관적으로 어떤 의미인지 받아드릴 수 있는 상황에서는 굳이 주석을 남길 필요는 없습니다.

2023-06-27 15:26 UTC, sunwootest commented on src/main/java/baseball/Application.java
> +			userGuessNumber = getUserGuessNumber();
선언과 동시에 초기화 하는 것이 더 잘 읽히는 코드입니다.

```java
String userGuessNumber = getUserGuessNumber();
```

2023-06-27 15:26 UTC, sunwootest commented on src/main/java/baseball/Application.java
> +			}
```java
if(repeateGame()){
    continue;
}
break;
```

이렇게 작성하면 `repeatGame()` 반환값에 따른 모든 경우를 코드에 표현할 수 있습니다.

2023-06-29 13:29 UTC, farmJun commented
리뷰해주신 것들 바탕으로 리팩토링 진행하였습니다! 다시 리뷰 부탁드리겠습니다!🔥

2023-06-29 14:20 UTC, KeonHee requested changes
아직 개별 함수들을 올바르게 구현하는 것 부터 마무리 되어야할 것 같습니다. 아래 항목들에 집중해서 리팩토링해주세요.

- 함수의 인터페이스만 봐도 이 함수가 어떤 역할을 하고 input/ouput에는 어떤 값들이 담기는지 추론이 가능해야한다.
  - 함수의 input과 output 타입에 대한 고민
  -  객체를 리턴 타입으로 사용할 수 있다.  
- input에 대한 예외처리(특히 파싱)

2023-06-29 14:20 UTC, KeonHee commented on src/main/java/baseball/Message.java
> +	public String getMessage() {
`toString` 메소드 override하면 더 깔끔할거 같네요


```java
System.out.println(Message.GUESS_NUMBER_REQUEST_MESSAGE);
// 숫자를 입력해주세요 : 
```

2023-06-29 14:20 UTC, KeonHee commented on src/main/java/baseball/Number.java
> +	public int getNumber() {
네이밍할 때에는 이 함수를 사용하는 입장에서 네이밍하면 좋습니다.

가령 `Number.NUMBER_OF_DIGITS.getNumber()`은 명확하긴 하지만 Number라는 단어가 중복됩니다.

이럴땐 그냥 `Number.NUMBER_OF_DIGITS.value()` or `Number.NUMBER_OF_DIGITS.get()` 이 정도로 줄여 써도 됩니다. 어차피 리턴 타입이 int라서 사용하는 입장에서 헷갈릴만한게 없죠?

2023-06-29 14:20 UTC, KeonHee commented on src/main/java/baseball/NumberManager.java
> +	}
1. int -> String -> int로 계속 타입을 변환하는 이유가 있나요? int만으로도 충분히 구현이 가능할 거 같은데요
2. 리턴 타입이 int고 로직을 보아하니 세 자리 정수인거같은데, 로직을 보지않고도 3자리 정수임을 파악할 수 있도록 리턴 타입을 바꿀 수 있을까요?

2023-06-29 14:20 UTC, KeonHee commented on src/main/java/baseball/NumberManager.java
> +		return Integer.parseInt(userGuessNumber);
코드 전체적으로 모든 파싱 과정에서 예외가 발생할 가능성이 있는데 예외 처리가 하나도 안된거 같네요.

특히 외부로부터 input을 받을 때에는 어떤 값이 들어올지 모르기 때문에 input을 받은 이후에는 input 값에 대한 검증절차가 필요합니다.

2023-06-29 14:20 UTC, KeonHee commented on src/main/java/baseball/NumberManager.java
> +		}
3자리 정수의 중복 체크를 이렇게 리소스를 많이 쓰면서 해야하는지 의문이 드네요.

참고로 저는 아래처럼 했습니다.
```java
if (num1 == num2 || num2 == num3 || num3 == num1) {
    throw new IllegalArgumentException("서로 다른 세 자리 정수를 입력해 주세요.");
}
```

2023-06-29 14:20 UTC, KeonHee commented on src/main/java/baseball/NumberManager.java
> +	public Queue<Integer> calculateStrikeBallCount(String randomNumber, String userGuessNumber) {
여기서 Queue를 사용한 이유는 무엇인가요?

2023-06-29 14:20 UTC, KeonHee commented on src/main/java/baseball/BaseballGame.java
> +			int ballCount = strikeBallQueue.poll();
실수로 순서가 바뀌면 대참사가 날거같네요. Queue말고 다른 타입을 고민해봅시다.

참고로 저는 `Score` 객체를 만들어서 리턴했습니다.

2023-06-29 16:03 UTC, farmJun commented on src/main/java/baseball/NumberManager.java
> +		int userInputNumber = Integer.parseInt(userInput);
여기서 String to int 파싱 할 때는 위에 있는 for-each 문에서 문자열이 숫자만으로 이루어졌는가에 대한 예외처리를 진행했다고 생각하여 파싱했습니다.

2023-06-29 16:42 UTC, farmJun commented
말씀해주신대로 객체를 리턴 타입으로 함으로써 최대한 함수의 인터페이스만 봐도 함수의 역할을 추론할 수 있도록 리팩토링 했습니다.
또 인풋 및 파싱 과정에서 발생할 수 있는 예외를 처리했습니다. 
혹시나 빠뜨린 부분이 있는지 말씀해주시면 감사하겠습니다!!

2023-06-30 11:10 UTC, sunwootest commented
라이브 코드리뷰 완료

2023-10-25 12:40 UTC, closed without merging