[숫자 야구 게임]이승철 과제 제출합니다
LandvibeDev/java-baseball pull request #12
Opened 2023-07-02 14:35 UTC by leesc0839

먼저 지적받은, 리펙토링 할 부분을 readme 파일에 나열하고
하나씩 고칠 때마다 commit을 하였습니다.

테스트 코드를 작성할 때,
어떻게 작성해야 잘 작성한 것인지 감이 오지 않아서 어려웠습니다.
System.out.print()가 잘 작동하는지 확인하기 위해 ByteArrayOutputStream, PrintStream 이라는 것을 썼는데 어떤 클래스인지 조금 더 공부해 보겠습니다.

감사합니다.

2023-07-03 15:10 UTC, KeonHee requested changes
추상화에 대한 시도는 박수 쳐줄만한데 경험부족으로 이한 디테일 부족, 기준점의 부재, 목적성 상실로 인해서 결론적으로 보기도 힘들고 추상화도 안된 코드가 된 것 같습니다.

다음 과제는 추상화부터 하려고 하지말고 그냥 C 처럼 절차적으로 먼저 구현한 뒤에 하나하나씩 고쳐가는 식으로 진행했으면 좋곗네요.

2023-07-03 15:10 UTC, KeonHee commented on src/main/java/baseball/AppConfig.java
> +public class AppConfig {
싱글톤을 의도한건가요?

싱글톤을 구현하는 방식은 되게 많은데 보통 `LazyHolder Singleton` 패턴으로 많이 구현하니까 검색해서 참고해보세요

2023-07-03 15:10 UTC, KeonHee commented on src/main/java/baseball/Application.java
> +        appConfig.baseBallGame().playBaseBallGame();
Class 이름만 보면 설정같은게 들어 있을거같은데 실제로는 Runner에 더 가깝네요.

2023-07-03 15:10 UTC, KeonHee commented on src/main/java/baseball/BaseBallGame.java
> +    public BaseBallGame(MakeRandomNumberService makeRandomNumberService, MakeInputNumberService makeInputNumberService, MakeScoreService makeScoreService, PrintScoreService printScoreService, CheckVa
의존성 주입을 할때 L-value는 보통 인터페이스로 구현합니다.

2023-07-03 15:10 UTC, KeonHee commented on src/main/java/baseball/constant/Number.java
> +    REPLAY_GAME(1), END_GAME(2), LENGTH_OF_INPUT(3);
너무 상관없는 것들이 하나의 Enum으로 묶여있는거 같네요.

2023-07-03 15:10 UTC, KeonHee commented on src/main/java/baseball/number/CheckValidNumberService.java
> +    public int convertToInt(String inputString) {
파싱 과정에서 발생할 수 있는 예외를 처리 해주는건 좋은 시도였습니다.

다만 여기서는 결과적으로 NumberFormatException 예외 대신 IllegalArgumentException가 발생하는 거 같은데요. 너무 안쪽 메소드에서 예외를 던지고 끝내면 나중에 어디서 예외가 발생하는지 찾기가 힘듭니다.  

그래서 메소드 끝에 예외를 던지는걸 아래처럼 표시해 주면 좋습니다.
- `public int convertToInt(String inputString)  throws IllegalArgumentException`

오히려 여기서는 NumberFormatException을 던지는걸 명시해주고 convertToInt 함수를 사용할때 catch 했으면 좋았을거 같아요.
- `public int convertToInt(String inputString)  throws NumberFormatException `

2023-07-03 15:10 UTC, KeonHee commented on src/main/java/baseball/number/MakeInputNumberService.java
> +        if (!checkValidNumberService.isValidNumberMap(inputNumberMap)) {
Service가 만능 단어가 된거같은데 경험 부족이라 생각하고 웃고 넘어갑니다ㅋㅋㅋ

이 경우에는 검증하는 역할을 하니 Validator 정도가 적당하겠네요.

2023-07-03 15:10 UTC, KeonHee commented on src/main/java/baseball/score/PrintScoreService.java
> +            System.out.print(ball + Message.BALL.get());
코드 전체적으로 함수를 되게 잘게 쪼개놨는데 그 기준을 잘 모르겠어요.

여기는 출력되는 조건을 판단하는 로직과 실제 출력하는 로직이 혼재해 있어서 쪼갠 의미가 없어보입니다.

2023-07-03 15:10 UTC, KeonHee commented on src/main/java/baseball/score/Score.java
> +        ball++;
이런 값을 담는 객체는 내부 변수를 immutable하게 유지하는 것이 좋습니다.

변수에 final 붙이고 리팩토링해보세요
```java
private final int strike;
private final int ball;
```

2023-07-03 15:10 UTC, KeonHee commented on src/main/java/baseball/score/Score.java
> +            System.out.println(Message.CLEAR_GAME.get());
아이디어는 좋았는데 출력하는 로직이 같이 있는게  아쉽네요.

2023-07-03 15:10 UTC, KeonHee commented on src/test/java/baseball/number/CheckValidNumberServiceTest.java
> +        Assertions.assertThat(length).isEqualTo(3);
상수들까지 테스트할 필요는 없습니다.

2023-07-03 15:10 UTC, KeonHee commented on src/test/java/baseball/number/CheckValidNumberServiceTest.java
> +        assertThat(checkValidNumberService.isValidNumberMap(duplicatedMap)).isEqualTo(false);
given-when-then 구조를 가져갈꺼면 아래처럼  분리해도 좋습니다

```java
// given
boolean expected = false
Map<Integer, Integer> zeroInMap = new HashMap<>();
zeroInMap.put(0, 0);
zeroInMap.put(1, 1);
zeroInMap.put(2, 2);

// when
boolean actual = checkValidNumberService.isValidNumberMap(zeroInMap);

// then
assertThat(expected).isEqualTo(actual);
```

2023-07-04 09:43 UTC, leesc0839 commented
좋은 피드백들 정말 감사합니다! 
추상화를 쓰는 이유를 전혀 생각하지 않았던 것 같습니다. 
그저 기능을 나누기에만 급급하고, 나누다가 의존성이 생기면 생성자 주입만 주구장창 하는 의미 없는 코드들이 되어버린 것 같습니다. 그로 인해 가독성도 매우 떨어지게 되었던 것 같습니다.

다음과제부터는 말씀대로 절차적으로 구현 후 고쳐가는 식으로 구현해보며, 추상화를 왜 쓰는지 생각하면서 리팩토링을 하겠습니다. 감사합니다!

2024-06-27 00:32 UTC, closed without merging