Leesewon00
LandvibeDev/java-baseball pull request #5
Opened 2023-06-29 10:51 UTC by leesewon00

이세원 과제 제출합니다 (1)

2023-06-29 11:08 UTC, sunwootest requested changes
잘 구현하셨습니다!

유지보수가 용이하게 코드를 리팩토링 해봅시다. 개선해야될 부분들이 많이 있지만 일단 리뷰해드린 내용을 바탕으로 개선해보세요 :)

2023-06-29 11:08 UTC, sunwootest commented on src/main/java/baseball/game/Game.java
> +    }
질문의 개수가 4개로 바뀌어도 유지보수가 용이하게 리팩토링 해봅시다.

2023-06-29 11:08 UTC, sunwootest commented on src/main/java/baseball/game/Game.java
> +        return makeQuestion();
변수명을 `flag`라고 지었을 때 어떤 역할을 하는지 파악하기 어렵습니다. `isDuplicated`로 바꾸면 가독성이 향상될 것 같습니다.

2023-06-29 11:08 UTC, sunwootest commented on src/main/java/baseball/game/Game.java
> +    }
early return을 하기 때문에 `else if` 와 `else`가 없어도 정상적으로 동작합니다.

`else if` -> `if`
`else` -> `제거`

2023-06-29 11:08 UTC, sunwootest commented on src/main/java/baseball/game/Game.java
> +            System.out.println("3개의 숫자를 모두 맞히셨습니다! 게임 종료");
출력관련 로직을 분리해봅시다. 출력메시지를 변경하라는 요구사항이 주어졌을 때 해당 메시지가 어디 있었는지 코드 전체를 뒤져야할 수 있습니다.

2023-06-29 11:39 UTC, KeonHee requested changes
기능은 얼추 잘 구현한거 같네요 👍

남은 시간 리팩토링에 집중해봅시다.

지금 단 코멘트말고도 리뷰할 건 많은데 너무 길어질까봐 일단 이 정도만 달았어요.
리뷰 없는 함수들도 다시한번 검토해보세요.

2023-06-29 11:39 UTC, KeonHee commented on src/main/java/baseball/game/Game.java
> +            int n = Randoms.pickNumberInRange(1, 9);
range가 2-7, 1-7로 바뀌어도 큰 변동이 없도록 수정해보세요.

2023-06-29 11:39 UTC, KeonHee commented on src/main/java/baseball/game/Game.java
> +        throw new IllegalArgumentException();
아래 비교 예시를 보고 이 함수를 리팩토링 해보세요.


### AS IS
```java
if (con1) {
   if (con2) {
       // 조건이 많아질 수 록 depth가 깊어져서 가독성이 떨어짐
       return result;
   }
   throw new IllegalArgumentException();
}
throw new IllegalArgumentException();
```


### TO BE
```java
if (!con1) {
   throw new IllegalArgumentException();
}
if (!con2) {
   throw new IllegalArgumentException();
}
return result;
```

2023-06-29 11:39 UTC, KeonHee commented on src/main/java/baseball/game/Game.java
> +                    ball++;
`question[i]==inputNumbers[j]` 조건이 중복되는데 중복되지 않도록 수정해보세요

2023-06-29 11:39 UTC, KeonHee commented on src/main/java/baseball/game/Game.java
> +        return Integer.toString(strike)+(ball);
객체로 만들어서 리턴하면 어떨까요?

2023-06-29 11:39 UTC, KeonHee commented on src/main/java/baseball/game/Game.java
> +    public boolean printResult(String check){
이 함수는 3개의 역할을 하고 있습니다. 모두 분리해보세요.
- ball/strike 개수에 따라서 어떤 메세지를 출력해야하는지 결정
- 메세지 출력
- 종료 조건 판단

2023-06-30 12:07 UTC, leesewon00 reviewed
[숫자 야구 게임] 이세원 과제수정본(1) 제출합니다
commit과 pr이 어색해서 분리해서 제출하지 못했는데
다음부터는 변경시마다 commit하여 제출하도록 노력하겠습니다.
코드리뷰 부탁드리겠습니다,,!

*배열 >> ArrayList
*변수명 변경
*else if , else 미사용
*조건문 형식 변경
*중복 조건문 삭제
*strike 와 ball 을 가지는 Count 객체 생성
*함수 역할 분리
*클래스 분리

2023-07-02 15:26 UTC, sunwootest requested changes
객체를 적극적으로 활용해봅시다. 메소드는 파라미터와 반환값이 존재하고 이를 어떻게 하면 활용할 수 있을지 고민하면 좋겠습니다. 

코드는 이전보가 훨씬 나아진 것 같습니다 :)

2023-07-02 15:26 UTC, sunwootest commented on src/main/java/baseball/game/Game.java
> +            }
while문을 탈출하려면 `break`를 사용하면 됩니다. result를 굳이 선언할 필요는 없어보입니다.

2023-07-02 15:26 UTC, sunwootest commented on src/main/java/baseball/game/Game.java
> +                Count count = check.checkResult(question, inputNumbers);
`Check`를 클래스의 필드로 설정해도 되지 않을까요?

2023-07-02 15:26 UTC, sunwootest commented on src/main/java/baseball/game/Game.java
> +        System.out.println("게임을 새로 시작하려면 1, 종료하려면 2를 입력하세요.");
출력을 다른 메소드로 분리시켜보세요.

2023-07-02 15:26 UTC, sunwootest commented on src/main/java/baseball/game/Input.java
> +        }
0과 3이라는 숫자에 의존하는 클래스가 되었습니다. 게임 규칙을 `길이가 4인 3-9사이 숫자`로 변경해도 약간의 코드수정만 필요하도록 리팩토링 해보세요.

2023-07-02 15:26 UTC, sunwootest commented on src/main/java/baseball/game/Print.java
> +}
메소드를 활용하면 `result`라는 변수를 이렇게 선언할 필요도 없지 않을까요?

2026-01-18 05:23 UTC, closed without merging