김수환 1차 pr입니다.
LandvibeDev/java-baseball pull request #7
Opened 2023-06-29 16:32 UTC by genius00hwan

예외테스트, 게임종료 후 재 시작 테스트 실패 했습니다.
코드 수정후 다시 재출 하겠습니다.

2023-06-30 07:40 UTC, sunwootest requested changes
알고리즘 문제 푸는 습관이 이번 과제에 그대로 반영된 것 같습니다. 객체지향적으로 설계를 해봅시다. 

요구사항을 충족하는 것이 1순위입니다. 하나의 메소드에 모든 요구사항을 다 포함시키고 리팩토링 하는 방법으로 진행해도 괜찮습니다.

2023-06-30 07:40 UTC, sunwootest commented on src/main/java/baseball/Game.java
> +	Judge judge = new Judge();
자바 빈 규약에 따른 클래스의 구성요소를 떠올리면 이렇게 필드를 선언하고 초기화 하는 것은 부자연스럽습니다. 물론 자바 빈 규약을 완전히 지킬 필요는 없지만 이런 방식은 알고리즘 문제 풀 때의 방식 같습니다.

2023-06-30 07:40 UTC, sunwootest commented on src/main/java/baseball/Game.java
> +	}
do-while문은 지양합시다. 코드 가독성이 떨어집니다.

2023-06-30 07:40 UTC, sunwootest commented on src/main/java/baseball/Game.java
> +	}
`출력`과 `입력에 대한 검증`을 다른 메소드로 분리해볼까요?

2023-06-30 07:40 UTC, sunwootest commented on src/main/java/baseball/Judge.java
> +	Target target = new Target();
초기화는 생성자를 통해서 진행하는 것이 낫습니다.

2023-06-30 07:40 UTC, sunwootest commented on src/main/java/baseball/Judge.java
> +	}
Java에서 Vector 사용은 지양하는 편입니다. 그 이유에 대해서 알아보시고 다른 대안을 적용해보세요.

2023-06-30 08:46 UTC, genius00hwan commented on src/main/java/baseball/Judge.java
> +	}
네 수정하도록 하겠습니다.

2023-07-01 06:43 UTC, genius00hwan reviewed
Readme 파일을 작성하고, 메시지, 상수 값등을 저장하는 클래스를 만들었습니다. 예외처리 클래스도 만들었습니다.
감사합니다

2023-07-02 07:59 UTC, genius00hwan reviewed
코드 리뷰 해주시면 감사하겠습니다!!

2023-07-02 09:52 UTC, genius00hwan reviewed
캡슐화를 위해 getter를 추가했습니다.

2023-07-03 11:52 UTC, sunwootest requested changes
오늘 설명해준 내용 바탕으로 객체지향적으로 리팩토링 해보세요! 
리뷰할 수 있는 부분들이 있는데 크게 건드리지 않았습니다 오늘 설명을 듣고나서 개선할 수 있을 것 같아서요.

2023-07-03 11:52 UTC, sunwootest commented on src/main/java/baseball/Constants.java
> +
패키지를 하나 생성해서 여러 클래스로 분리하는 편이 나아보입니다.

2023-07-03 11:52 UTC, sunwootest commented on src/main/java/baseball/ExceptionHandler.java
> +	}
예외처리를 별도의 클래스에서 처리해줄 필요가 있을까요?

2023-07-03 11:52 UTC, sunwootest commented on src/main/java/baseball/Game.java
> +			this.play();
`play()`라고만 작성해도 충분합니다.

2023-07-03 11:52 UTC, sunwootest commented on src/main/java/baseball/Game.java
> +		System.out.print(getGuessNumberMessage());
출력을 별도의 메소드로 분리해봅시다. 출력내용을 분리하는 것도 좋지만 sout 전체를 분리하는 편이 나아보입니다.

2023-07-04 14:25 UTC, genius00hwan reviewed
상수 패키지를 따로 만들고 printer 클래스를 따로 만들었습니다.

2024-09-22 06:48 UTC, closed without merging